# Welcome to Jekyll!
#

# Site settings
title: Alessandro Caratelli
description: |
  PhD student in Microelectronics
description2: |
  Digital Integrated Circuits Design and Verification
owner: Alessandro Caratelli # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: caratelli.a@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acaratel.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://www.linkedin.com/in/alessandrocaratelli
  facebook-official: https://www.facebook.com/AlessandroCaratelli
  google-plus-square: https://plus.google.com/+AlessandroCaratelli
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
